### ISSUE TITLE
A little unrelated

### ISSUE THREAD

**Issue by cxeri** [B-Woody/CSV-to-LDAP-Attribute#1]
Hi Brenden,  sorry for contacting you like this but wanting to get more insight into deploying openshift cluster with ansible.  I am just starting creating the role and playbooks but getting a little stuck.  Are you able to help?

Hope all is wonderful,

Caroline

**Comment by B-Woody** [comment]
Hey! Hope you're well! I haven't had much to do with OpenShift (yet) so unfortunately I can't really be of any help.
